version: '3'

env:
  DEV_PORT: 8000
  DEV_LOG_LEVEL: "DEBUG"
  DEV_DATA_FOLDER: ".local/data"

tasks:
  dev:
    cmds:
      - go run main.go --port ${DEV_PORT} --log-level ${DEV_LOG_LEVEL} --data ${DEV_DATA_FOLDER} --cors "*"

  clean:
    silent: true
    cmds:
      - rm -rf build/
  generate:
    silent: true
    cmds:
      - rm -rf ./pkg/api/*
      - openapi-generator-cli generate -c openapitools-go-server.json
      - openapi-generator-cli generate -c openapitools-yaml.json
  build:
    silent: true
    deps:
      - clean
    cmds:
      - go build -o build/psapi
      
