// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package api




type PokemonDetail struct {

	// The symbol of the pokemon
	Symbol string `json:"symbol,omitempty"`

	// The number of the pokemon
	Number int32 `json:"number,omitempty"`

	MainForm FormDetail `json:"main_form,omitempty"`
}

// AssertPokemonDetailRequired checks if the required fields are not zero-ed
func AssertPokemonDetailRequired(obj PokemonDetail) error {
	if err := AssertFormDetailRequired(obj.MainForm); err != nil {
		return err
	}
	return nil
}

// AssertPokemonDetailConstraints checks if the values respects the defined constraints
func AssertPokemonDetailConstraints(obj PokemonDetail) error {
	if err := AssertFormDetailConstraints(obj.MainForm); err != nil {
		return err
	}
	return nil
}
