// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package api




type GetPokemons200Response struct {

	Content []PokemonThumbnail `json:"content,omitempty"`

	// The number of the page
	Number int32 `json:"number,omitempty"`

	// The size of the page
	Size int32 `json:"size,omitempty"`

	// The total number of elements
	Total int32 `json:"total,omitempty"`
}

// AssertGetPokemons200ResponseRequired checks if the required fields are not zero-ed
func AssertGetPokemons200ResponseRequired(obj GetPokemons200Response) error {
	for _, el := range obj.Content {
		if err := AssertPokemonThumbnailRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertGetPokemons200ResponseConstraints checks if the values respects the defined constraints
func AssertGetPokemons200ResponseConstraints(obj GetPokemons200Response) error {
	for _, el := range obj.Content {
		if err := AssertPokemonThumbnailConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
