openapi: "3.0.0"

info:
  version: 0.0.1
  title: Pokemon Studio API
  description: API for the Pokemon Studio
servers:
  - url: "http://localhost:8000/api"
paths:
  /pokemon:
    $ref: "./paths/pokemon.yml"
  /pokemon/{symbol}:
    $ref: "./paths/pokemonDetails.yml"
  /pokemon/{symbol}/{form}:
    $ref: "./paths/pokemonForm.yml"
