// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package psapigen

import (
	"context"
	"net/http"
)

// PokemonAPIRouter defines the required methods for binding the api requests to a responses for the PokemonAPI
// The PokemonAPIRouter implementation should parse necessary information from the http request,
// pass the data to a PokemonAPIServicer to perform the required actions, then write the service results to the http response.
type PokemonAPIRouter interface {
	GetPokemon(http.ResponseWriter, *http.Request)
	GetPokemonDetails(http.ResponseWriter, *http.Request)
	GetPokemonForm(http.ResponseWriter, *http.Request)
}

// PokemonAPIServicer defines the api actions for the PokemonAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type PokemonAPIServicer interface {
	GetPokemon(context.Context, int32, int32, string) (ImplResponse, error)
	GetPokemonDetails(context.Context, string, string) (ImplResponse, error)
	GetPokemonForm(context.Context, string, int32, string) (ImplResponse, error)
}
