// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package psapigen

// TypeDetails - An object containing detailed data of a pokemon type
type TypeDetails struct {

	// The translated name of the pokemon type
	Name string `json:"name,omitempty"`

	// The symbol of the pokemon type
	Symbol string `json:"symbol,omitempty"`

	// The color of the pokemon type
	Color string `json:"color,omitempty"`

	// The damage inflicted by this type
	TypeDamage []TypeDamage `json:"typeDamage,omitempty"`
}

// AssertTypeDetailsRequired checks if the required fields are not zero-ed
func AssertTypeDetailsRequired(obj TypeDetails) error {
	for _, el := range obj.TypeDamage {
		if err := AssertTypeDamageRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTypeDetailsConstraints checks if the values respects the defined constraints
func AssertTypeDetailsConstraints(obj TypeDetails) error {
	for _, el := range obj.TypeDamage {
		if err := AssertTypeDamageConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
