// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package psapigen

// Page - A page of content
type Page struct {

	// Contains the items of the page
	Content []string `json:"content,omitempty"`

	// The number of the page
	Number int32 `json:"number,omitempty"`

	// The size of the page
	Size int32 `json:"size,omitempty"`

	// The total number of elements
	Total int32 `json:"total,omitempty"`
}

// AssertPageRequired checks if the required fields are not zero-ed
func AssertPageRequired(obj Page) error {
	return nil
}

// AssertPageConstraints checks if the values respects the defined constraints
func AssertPageConstraints(obj Page) error {
	return nil
}
