// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package webgen

// TypeDamage - An object containing the damage against a type
type TypeDamage struct {

	// The type
	DefensiveType string `json:"defensiveType,omitempty"`

	// The damage
	Factor *float32 `json:"factor,omitempty"`
}

// AssertTypeDamageRequired checks if the required fields are not zero-ed
func AssertTypeDamageRequired(obj TypeDamage) error {
	return nil
}

// AssertTypeDamageConstraints checks if the values respects the defined constraints
func AssertTypeDamageConstraints(obj TypeDamage) error {
	return nil
}
