// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package webgen

type PokemonPage struct {
	Content []PokemonThumbnail `json:"content,omitempty"`

	// The number of the page
	Number int32 `json:"number,omitempty"`

	// The size of the page
	Size int32 `json:"size,omitempty"`

	// The total number of elements
	Total int32 `json:"total,omitempty"`
}

// AssertPokemonPageRequired checks if the required fields are not zero-ed
func AssertPokemonPageRequired(obj PokemonPage) error {
	for _, el := range obj.Content {
		if err := AssertPokemonThumbnailRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertPokemonPageConstraints checks if the values respects the defined constraints
func AssertPokemonPageConstraints(obj PokemonPage) error {
	for _, el := range obj.Content {
		if err := AssertPokemonThumbnailConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
